name: Last Binary Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.24.5
      uses: actions/setup-go@v1
      with:
        go-version: 1.24.5
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: COMMITHASH=$(git rev-parse --short HEAD) && go build -o helloworld -ldflags "-X main.CommitHash=$COMMITHASH" .
